baseURL = "https://project-gutenberg.github.io/nCovMemory-Web/"
DEPLOY_PRIME_URL = "https://project-gutenberg.github.io/nCovMemory-Web/"
site_url = "https://project-gutenberg.github.io/nCovMemory-Web/"
relativeURLs = true
languageCode = "zh-cn"
title = "2020新冠肺炎记忆"
author = "Freedom of Speech"
description = "收录了2020年新型冠状病毒肺炎（ COVID-19 ）相关的媒体报道、非虚构作品和亲历者个人叙述。"
theme = "northendlab"
googleAnalitycsID = "UA-151212685-7"
copyright = "Copyright © nCovMemory"
enableRobotsTXT = true
disableAliases = true
googleAnalytics = "UA-151212685-7"
summaryLength = 50
media_folder = "site/static/images/uploads"
public_folder = "images/uploads"
disqusShortname = "pin-cong-jing-xuan"
######################### Default Parameters ###########################
[params]
# home
home = "Home"
# logo
logo = "/images/logo.png"
DEPLOY_PRIME_URL = "https://project-gutenberg.github.io/nCovMemory-Web/"
googleAnalitycsID = "UA-151212685-7"